clc;
clear all;
close all;

repo_root = fileparts(mfilename('fullpath'));
input_path = fullfile(repo_root, 'S2022Sap.xlsx');
[data text raw]=xlsread(input_path);
text=char(text(1,:));
[p1,q]=size(text);
temperature=zeros(p1,1);
for p=1:p1
temp=text(p,:);
temp(temp=='K')=[];
temp=str2double(temp);
temperature(p)=temp;
end;
temperature=temperature(~isnan(temperature));

% Check that the main workflow includes the paper-based lambda logic and
% the requested validation metrics before running.
analysis_file = fullfile(repo_root, 'drt_input_analysis_matlab2011.m');
if exist(analysis_file, 'file') == 2
	fid = fopen(analysis_file, 'r');
	src = '';
	if fid > 0
		src = fread(fid, '*char')';
		fclose(fid);
	end

	has_paper_lambda = ~isempty(strfind(src, 'ChemElectroChem')) && ...
		~isempty(strfind(src, 'rid')) && ...
		~isempty(strfind(src, 'resample_var'));
	has_cv = ~isempty(strfind(src, 'cv_real')) && ...
		~isempty(strfind(src, 'cv_imag'));
	has_residual = ~isempty(strfind(src, 'Mean absolute residual')) || ...
		~isempty(strfind(src, 'mean_resid'));
	has_kk = ~isempty(strfind(src, 'perform_kk_test_matlab2011'));

	fprintf('Workflow feature check before run:\n');
	fprintf('  Paper-based lambda (RID + CV + variance): %d\n', has_paper_lambda);
	fprintf('  CV metrics (Re/Im):                       %d\n', has_cv);
	fprintf('  Residual calculation/reporting:           %d\n', has_residual);
	fprintf('  KK test execution:                        %d\n', has_kk);
else
	fprintf('Warning: analysis file not found for feature check: %s\n', analysis_file);
end

fprintf('\nRunning original workflow with paper-based lambda selection...\n');
drt_input_analysis_matlab2011(repo_root,input_path,temperature,data);

fprintf('\nExpected output files generated by this run:\n');
fprintf('  %s\n', fullfile(repo_root, 'kk_result.xlsx'));
fprintf('  %s\n', fullfile(repo_root, 'sensitivity_result.xlsx'));
fprintf('  %s\n', fullfile(repo_root, 'lambda_perturbation_result.xlsx'));