clc;
clear all;
close all;

repo_root = fileparts(mfilename('fullpath'));
input_path = fullfile(repo_root, 'S2022Sap.xlsx');
[data, text_hdr] = xlsread(input_path);
[~, base_name, ~] = fileparts(input_path);
sample_tag = lower(regexprep(base_name, '[^a-zA-Z0-9]', ''));
if isempty(sample_tag)
    sample_tag = 'sample';
end

temperature = zeros(0, 1);
if ~isempty(text_hdr)
    header_cells = text_hdr(1, :);
    for k = 1:numel(header_cells)
        tok = header_cells{k};
        if ischar(tok)
            tok = strtrim(tok);
            tok(tok == 'K' | tok == 'k') = [];
            val = str2double(tok);
            if ~isnan(val)
                temperature(end + 1, 1) = val; %#ok<AGROW>
            end
        end
    end
end

% Check that the main workflow file exists before running.
analysis_file = fullfile(repo_root, 'drt_input_analysis_matlab2011.m');
if exist(analysis_file, 'file') == 2
    fprintf('Workflow file found: %s\n', analysis_file);
else
    error('Analysis file not found: %s', analysis_file);
end

fprintf('\nRunning workflow with GCV lambda selection (Im inversion, Re+Im cross-validation)...\n');
drt_input_analysis_matlab2011(repo_root,input_path,temperature,data);

fprintf('\nExpected output files generated by this run:\n');
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_analysis_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_peak_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_kk_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_sensitivity_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_lambda_perturbation_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_peak_detail_result.xlsx', sample_tag)));
fprintf('  %s\n', fullfile(repo_root, sprintf('%s_temperature_plot_data.xlsx', sample_tag)));