clc;
clear all;
close all;

repo_root = fileparts(mfilename('fullpath'));
input_path = fullfile(repo_root, 'S2022Sap.xlsx');
[data text raw]=xlsread(input_path);
text=char(text(1,:));
[p1,q]=size(text);
temperature=zeros(p1,1);
for p=1:p1
temp=text(p,:);
temp(temp=='K')=[];
temp=str2double(temp);
temperature(p)=temp;
end;
temperature=temperature(~isnan(temperature));

% Check that the main workflow file exists before running.
analysis_file = fullfile(repo_root, 'drt_input_analysis_matlab2011.m');
if exist(analysis_file, 'file') == 2
    fprintf('Workflow file found: %s\n', analysis_file);
else
    error('Analysis file not found: %s', analysis_file);
end

fprintf('\nRunning workflow with GCV lambda selection (Im inversion, Re+Im cross-validation)...\n');
drt_input_analysis_matlab2011(repo_root,input_path,temperature,data);

fprintf('\nExpected output files generated by this run:\n');
fprintf('  %s\n', fullfile(repo_root, 'kk_result.xlsx'));
fprintf('  %s\n', fullfile(repo_root, 'sensitivity_result.xlsx'));
fprintf('  %s\n', fullfile(repo_root, 'lambda_perturbation_result.xlsx'));